# These are supported funding model platforms

github: [mahisataruna]
open_collective: # Replace with a single Open Collective username
ko_fi: algorithmdev # Replace with a single Ko-fi username
buy_me_a_coffee: algorithmdev # Replace with a single Buy Me a Coffee username
custom: ["https://kreapic-web.vercel.app/"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
